force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Instructor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/LoadDataTestFactory.cls
public with sharing class LoadDataTestFactory {

    public static List<Course__c> loadCourses() {
        return Test.loadData(Course__c.sObjectType, 'TestCourses');
    }

    public static List<Certification__c> loadCertifications() {
        return Test.loadData(Certification__c.sObjectType, 'TestCertifications');
    }

    public static List<Account> loadAccounts() {
        return Test.loadData(Account.sObjectType, 'TestAccounts');
    }

    public static List<User> createUsers() {
        Id instructorProfileId = [SELECT Id FROM Profile WHERE Name = 'Instructor' LIMIT 1].Id;

        List<User> users = new List<User>();

        User instructor1 = new User(Username='mholmes@300321em.example.com',
                                            FirstName='Minnie', LastName='Holmes',
                                            email='mholmes@example.com',
                                            alias='mholmes',
                                            CommunityNickname='mholmes',
                                            TimeZoneSidKey='America/Los_Angeles',
                                            LocaleSidKey='en_US', 
                                            EmailEncodingKey='UTF-8',
                                            ProfileId=instructorProfileId, 
                                            LanguageLocaleKey='en_US'
                                           );
        users.add(instructor1);
        User instructor2 = new User(Username='nsanchez@300321em.example.com',
                                            FirstName='Minnie', LastName='Sanchez',
                                            email='nsanchez@example.com',
                                            alias='nsanchez',
                                            CommunityNickname='nsanchez',
                                            TimeZoneSidKey='America/Los_Angeles',
                                            LocaleSidKey='en_US', 
                                            EmailEncodingKey='UTF-8',
                                            ProfileId=instructorProfileId, 
                                            LanguageLocaleKey='en_US'
                                           );
        users.add(instructor2);

        return users;
    }
}