force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Instructor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Certification_Date__c.field-meta.xml
<CustomField>
    <fullName>Certification_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Certification Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Daily_Rate__c.field-meta.xml
<CustomField>
    <fullName>Daily_Rate__c</fullName>
    <label>Daily Rate</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Instructor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CertificationTriggerHnadler_Test.cls
@isTest
private class CertificationTriggerHnadler_Test {
    
    @TestSetup
    static void setupData(){
        List<User> testInstructors = LoadDataTestFactory.createUsers();
        List<Course__c> testCourses = LoadDataTestFactory.loadCourses();
        List<Certification__c> testCertifications = LoadDataTestFactory.loadCertifications();
        insert testInstructors;
    }

    @isTest
    static void insertCertification() {
        List<Course__c> activeCourse = [SELECT Id
                                        FROM Course__c
                                        LIMIT 1];
        Course__c course = activeCourse[0];

        Profile instructorP = [SELECT Id FROM Profile WHERE Name='Instructor'];
        List<User> instructors = [SELECT Id, Username FROM User WHERE profileId = :instructorP.Id LIMIT 2];

        Integer preCertCount = 0;
        Integer postCertCount = 0;
        Integer preCertCountInst2 = 0;
        Integer postCertCountInst2 = 0;

        System.runAs(instructors[0]) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++preCertCount;
                }
            }
        }

        System.runAs(instructors[1]) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++preCertCountInst2;
                }
            }
        }

        Test.startTest();

        Certification__c certification = new Certification__c();
        certification.Course__c = course.Id;
        certification.Instructor__c = instructors[0].Id;
        certification.Daily_Rate__c = 1;
        certification.Certification_Date__c = Date.today();

        List<Certification__c> certifications = new List<Certification__c>();
        certifications.add(certification);
        Database.SaveResult[] saveResults = Database.insert(certifications, false);

        Test.stopTest();

        Integer errorCount = 0;
        Integer insertCount = 0;

        for (Database.SaveResult sr : saveResults) {
            if (!sr.isSuccess()) {
                ++errorCount;
            } else {
                ++insertCount;
            }
        }

        System.runAs(instructors[0]) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++postCertCount;
                }
            }
        }

        System.runAs(instructors[1]) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++postCertCountInst2;
                }
            }
        }

        // System.debug(preCertCount);
        // System.debug(postCertCount);
        // System.debug(preCertCountInst2);
        // System.debug(postCertCountInst2);
        // System.debug(insertCount);

        System.assertEquals(0, errorCount);
        System.assertEquals(1, insertCount);
        System.assertEquals(1, postCertCount - preCertCount);
        System.assertEquals(0, postCertCountInst2 - preCertCountInst2);

    }

    @isTest
    static void insertCertificationBulk() {
        List<Course__c> activeCourse = [SELECT Id
                                        FROM Course__c
                                        LIMIT 1];
        Course__c course = activeCourse[0];

        Profile instructorP = [SELECT Id FROM Profile WHERE Name='Instructor'];
        List<User> instructors = [SELECT Id, Username FROM User WHERE profileId = :instructorP.Id LIMIT 2];

        Integer preCertCount = 0;
        Integer postCertCount = 0;
        Integer preCertCountInst2 = 0;
        Integer postCertCountInst2 = 0;

        System.runAs(instructors[0]) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++preCertCount;
                }
            }
        }

        System.runAs(instructors[1]) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++preCertCountInst2;
                }
            }
        }

        Test.startTest();

        List<Certification__c> certifications = new List<Certification__c>();

        for (Integer i = 0; i < 205; i++) {
            Certification__c certification = new Certification__c();
            certification.Course__c = course.Id;
            certification.Instructor__c = instructors[0].Id;
            certification.Daily_Rate__c = 1;
            certification.Certification_Date__c = Date.today();   
            
            certifications.add(certification);
        }
        
        Database.SaveResult[] saveResults = Database.insert(certifications, false);

        Test.stopTest();

        Integer errorCount = 0;
        Integer insertCount = 0;

        for (Database.SaveResult sr : saveResults) {
            if (!sr.isSuccess()) {
                ++errorCount;
            } else {
                ++insertCount;
            }
        }

        System.runAs(instructors[0]) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++postCertCount;
                }
            }
        }

        System.runAs(instructors[1]) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++postCertCountInst2;
                }
            }
        }

        // System.debug(preCertCount);
        // System.debug(postCertCount);
        // System.debug(preCertCountInst2);
        // System.debug(postCertCountInst2);
        // System.debug(insertCount);

        System.assertEquals(0, errorCount);
        System.assertEquals(205, insertCount);
        System.assertEquals(205, postCertCount - preCertCount);
        System.assertEquals(0, postCertCountInst2 - preCertCountInst2);

    }

    @isTest
    static void updateCertification() {
        List<Certification__c> activeCert = [SELECT Id, Certification_Date__c, Course__c, CreatedById, CreatedDate, Daily_Rate__c, IsDeleted, Name, Instructor__c, LastModifiedById, LastModifiedDate, LastReferencedDate, LastViewedDate, OwnerId, SystemModstamp
                                             FROM Certification__c
                                             LIMIT 1];
        Certification__c certToUpdate = activeCert[0];

        Profile instructorP = [SELECT Id FROM Profile WHERE Name='Instructor'];
        List<User> instructors = [SELECT Id, Username FROM User WHERE profileId = :instructorP.Id LIMIT 2];
        USER originalInstructor = [SELECT Id FROM User WHERE Id = :certToUpdate.Instructor__c LIMIT 1];

        Integer preCertCount = 0;
        Integer postCertCount = 0;
        Integer preCertCountInst2 = 0;
        Integer postCertCountInst2 = 0;

        System.runAs(originalInstructor) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++preCertCount;
                }
            }
        }

        System.runAs(instructors[0]) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++preCertCountInst2;
                }
            }
        }

        Test.startTest();

        certToUpdate.Instructor__c = instructors[0].Id;

        List<Certification__c> certifications = new List<Certification__c>();
        certifications.add(certToUpdate);
        Database.SaveResult[] saveResults = Database.update(certifications, false);

        Test.stopTest();

        Integer errorCount = 0;
        Integer insertCount = 0;

        for (Database.SaveResult sr : saveResults) {
            if (!sr.isSuccess()) {
                ++errorCount;
                System.debug(sr.getErrors()[0].getMessage());
            } else {
                ++insertCount;
            }
        }

        System.runAs(originalInstructor) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++postCertCount;
                }
            }
        }

        System.runAs(instructors[0]) {
            for (List<Certification__c> certs : [SELECT Id FROM Certification__c]) {
                for (Certification__c cert : certs) {
                    ++postCertCountInst2;
                }
            }
        }

        // System.debug(preCertCount);
        // System.debug(postCertCount);
        // System.debug(preCertCountInst2);
        // System.debug(postCertCountInst2);
        // System.debug(insertCount);

        System.assertEquals(0, errorCount);
        System.assertEquals(1, insertCount);
        System.assertEquals(-1, postCertCount - preCertCount);
        System.assertEquals(1, postCertCountInst2 - preCertCountInst2);

    }

    
}